<?php
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_form_FORM_ID_alter() for the News content type form.
 */
function custom_duplicate_form_node_news_form_alter(&$form, FormStateInterface $form_state) {
  $form['#validate'][] = 'custom_duplicate_validate_news';
}

/**
 * Custom validation callback to prevent duplicate News content.
 */
function custom_duplicate_validate_news($form, FormStateInterface $form_state) {
  
  $title = $form_state->getValue('title');
//   $tags_field_values = $form_state->getValue('field_news_tags'); 

//   $tags = array_column($tags_field_values, 'target_id');

  
  $query = \Drupal::entityQuery('node');
  $query->condition('type', 'news'); 
  $query->condition('title', $title);
//   $query->condition('field_news_tags.target_id', $tags, 'IN');
  $query->accessCheck(FALSE);

  $count = $query->count()->execute();

  
  if ($count > 0) {
    $form_state->setErrorByName('title', 'Similar News content with the same title and tags already exists.');
  }
}
