<?php
// use Symfony\Component\HttpFoundation\RedirectResponse;
// use Drupal\Core\Url;
// /**
//  * Implements hook_user_login().
//  */
// function login_dashboard_user_login(&$edit, $account) {
//   if (in_array('reporter', $account->getRoles())) {
//     $path = 'reporter-dashboard';
//     $url = Url::fromUserInput($path)->toString();
//     $response = new RedirectResponse($url);
//     $response->send();
//   }    
// }